### ISSUE TITLE
Redesign property details

### ISSUE THREAD

**Issue by entrxyz** [EnterDAO/LandWorks-FE#174]
This is the map + details

**Design**: https://www.figma.com/file/gMFxv9DjmUkHbZQSe4lu5E/EnterDAO-Projects?node-id=4485%3A9928

We'll need to account for two states:
- Land
- Estate
- Static Map

**Comment by StilyanMitrev** [comment]
2 comments from @failfmi still to be resolved - to be kept in backlog until Mkhaylo's back

**Comment by StilyanMitrev** [comment]
Several items still to be addressed:

1. The margins of the "Rent now" and "View in metaverse" buttons to be fixed.
2. The paddings of the "View in metaverse" button to be fixed.
3. The "You" icon in the rent history to be the same as in the designs.
4. The tooltip at the bottom of the card is visible only for estates? It doesn't show for Lands.
5. The estate tooltip shows only a single coordinate.
