### ISSUE TITLE
WIP Edit, Delist or Stake a listed Property

### ISSUE THREAD

**Issue by entrxyz** [EnterDAO/LandWorks-FE#204]
**Design**: [here](https://www.figma.com/file/gMFxv9DjmUkHbZQSe4lu5E/EnterDAO-Projects?node-id=4830%3A16060)

When the user opens a property he listed, then he should have the following actions:
- Delist (similar to Withdraw in the current implementation)
- Edit -> opens the Edit screen
- Stake

Here is a screen, where you see the three actions: [here](https://www.figma.com/file/gMFxv9DjmUkHbZQSe4lu5E/EnterDAO-Projects?node-id=4752%3A11687)
**IMPORTANT**: Since this is your property, you should not have a Rent button, but you can "View on Metaverse". There will be a "Claim Rent" button if there is a rent to be claimed.

**Comment by StilyanMitrev** [comment]
that's done in last sprint
