### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by StilyanMitrev** [EnterDAO/LandWorks-FE#251]
**Overview**: The notification component will allow users to track events associated with their properties and engagement within LandWorks. As a first release of the notifications component we won't track the state of the notifications (tracking if they are read or not). This will allow for a faster implementation but at the cost of UX. At a later stage we might add a db tracking the state.

**Reasoning**: There are 3 main reasons for the notification component:
1.  Notifications are a must have feature for majority of similar marketplace applications
2. Notifications might increase user engagement as they will be prompting further/continuous actions
3. Notifications will act as the gateway for the most requested community feature - chat. We will be using blockscan's chat to facilitate it.

**Caters to**: Tenant and Landlords

**Product Requirements**:
At the moment we don't want to store states of notifications as this will require a database and a more substantial backend development. As a first release for the notifications feature we will use the login cookies of users. We will use login timestamps which will determine if a notification is new or not. We do have the following risk - if a user logs in form a different device we will show them everything. But as a first release for our limited userbase this feature will bring value.

We will have a total of 5 types of notifications. 
All notifications will have actions associated with them.
All notifications will have a timestamp. Timestamps to be displayed only in seconds, minutes, hours, days and rounded down.
We need to display 6 notifications and all the other should load on scroll.
We would also need a mark all as read button which will be stored in session.
All 4 notifications associated with properties should be available for all supported metaverses.

Notifications:

1. We need to notify landlord and tenants for new chats and redirect them to Blockscan's platform in order to chat with each other. We need to fetch unread counts from Blockscans' API in order to notify both tenants and landlords for new chat messages. 
ACTION - "CHAT" - on click should redirect to blockscan's chat.

2. We need to notify landlords when a listed property of theirs is rented. 
ACTION - "LIST MORE" - on click should open the Listing wizard.

3. We need to notify landlords when their rented property has become available. 
ACTION - "PROMOTE" - on click should open twitter just like the share button in the property details.

4. We need to notify tenants when they are halfway trhoygh their rent.
ACTION - "RENT AGAIN" - on click should open property details.

5. We need to notify tenants when their rents has expired. 
ACTION - "RENT AGAIN" - on click should open property details.

**Design**: https://www.figma.com/file/gMFxv9DjmUkHbZQSe4lu5E/EnterDAO-Projects?node-id=8386%3A19165

**Marketing**: TBD

**Comment by mishaadzh** [comment]
@StilyanMitrev we will be removing CLAIMED button for now, since it's difficult to fetch this information
cc @failfmi
