### ISSUE TITLE
As a user I want to have a dedicated notifications button so I can track events associated with my wallet

### ISSUE THREAD

**Issue by StilyanMitrev** [EnterDAO/LandWorks-FE#253]
We need to add a dedicated notifications button which will be:
- Present on all pages of the dapp once a wallet is connected. The button should be next to the wallet component [as per design](https://www.figma.com/file/gMFxv9DjmUkHbZQSe4lu5E/EnterDAO-Projects?node-id=8386%3A19592). 
- The notifications component should reveal on click. Once clicked we should show the notifications list [as per design](https://www.figma.com/file/gMFxv9DjmUkHbZQSe4lu5E/EnterDAO-Projects?node-id=7339%3A17348). When clicked again, the notifications component should close.
- The notification button should have a blue dot if there are new unread notifications associated with the connected wallet. Unread notifications are such which are associated with the user ever since his/her last login (based on cookies). If user logs in from a new device (no cookies associated), then we should show all notifications associated with the wallet as new.
- We need to have an empty state for the notifications component for situations when there are no notifications associated with the connected wallet. Empty state design [here](https://www.figma.com/file/gMFxv9DjmUkHbZQSe4lu5E/EnterDAO-Projects?node-id=7339%3A16914).

Overall design of the component [is located here](https://www.figma.com/file/gMFxv9DjmUkHbZQSe4lu5E/EnterDAO-Projects?node-id=5387%3A19373).

AC1: Given I'm browsing the dapp and i have connected my wallet, I should always have the notifications button at disposal.
AC2: Given I'm clicking on the notifications button then the notification component should open and close.
AC3: Given I'm connecting my wallet, then the dapp should show me all the notifications associated with my wallet since my last login.
AC4: Given I'm connecting my wallet for the first time from a device, then the dapp should show me all notifications associated with my wallet
AC5: Given I'm a new user and I haven't interacted with LandWorks so fat, then the notification component should show an empty state when clicked.

**Comment by StilyanMitrev** [comment]
On scroll the component widens.
Ensure it keeps the same width when scrolling.
![2022-05-16 13.52.42.gif](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/b9646770-d53a-41c7-9df0-2c844420e346)

**Comment by StilyanMitrev** [comment]
When the notification component is opened there seems to be a glitch - the scroll bar changes and some components move a bit (for the no map view) and the map refreshes and moves (for the Decentraland map view):

![2022-05-17 09.03.21.gif](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/734b4ca1-2263-4f9c-a3b2-31d253040c9e)

![2022-05-17 09.04.07.gif](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/99895127-27e1-47e2-83b6-69307db37995)

**Comment by StilyanMitrev** [comment]
We might have cases where the names of the properties will be too long. In those cases the subtext of the notification will be cut. Can we make the following changes:
- If a subtext is > 

![Screenshot 2022-05-17 at 9.19.05.png](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/69c59d24-cf65-4471-9afb-b470c031fe56)

**Comment by StilyanMitrev** [comment]
1. If I open a property from any notification in a new tab (mid button click), on the new page, the wallet is disconnected.
2. My bad here but can we change the animation to be as follows:
- text is cut off -> 1 sec delay -> text slides right to left -> animation end as the last character fits -> 1 sec delay -> it goes back to its original state.
![2022-05-26 13.37.12.gif](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/d7fb7adc-bd0f-4675-92fc-61912f7d8445)

**Comment by mishaadzh** [comment]
@StilyanMitrev 
the problem with mid button click and wallet disconnect is because we storing wallet data in session storage which disappears when we open web site from new tab since it's a new session started and we don't have info about connected wallet
Possible solutions is to use localstorage, but it can affect whole website logic
Need attention from @failfmi

**Comment by mishaadzh** [comment]
@StilyanMitrev animation will be fixed, just need some time

**Comment by StilyanMitrev** [comment]
skip the part with the middle button open in new tab

**Comment by StilyanMitrev** [comment]
Not sure what's the trigger for the animation but on my end it's inconsistent.
recording1 shows how the animation doesn't start
recording2 shows how the animation starts but i'm not sure how

![2022-06-03 08.49.18.gif](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/39476387-0849-4132-b60d-982d07be9f4d)
![2022-06-03 08.53.20.gif](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/d06ff042-7de4-4097-b3cc-31d97efe249f)
