### ISSUE TITLE
2 columns in explore page

### ISSUE THREAD

**Issue by StilyanMitrev** [EnterDAO/LandWorks-FE#262]
Update: define min/max widths for cards so they don;t look squished when 3.

At the moment when you open the explore page you get 3 columns of property cards (standard macbook resolution)![Screenshot 2022-03-09 at 4.42.22 PM.png](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/827afa76-f781-4946-913a-cc8f90c2617d)

But the design indicates we need 2 columns:
![Screenshot 2022-03-09 at 4.43.11 PM.png](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/eb84d8e4-c2ee-41e4-8ca6-a19f03cd0266)

**Comment by xdemocle** [comment]
but hey, this is a very wide resolution of your example and indeed I provided three columns because just 2 would be very silly wider. For the resolution of the Figma example. the app shows correctly the 2 columns. try to resize the window please.

**Comment by entrxyz** [comment]
Confirmed.
