### ISSUE TITLE
Breadcrumb Explore page buttons lead to the old "all" view of the Explore page

### ISSUE THREAD

**Issue by StilyanMitrev** [EnterDAO/LandWorks-FE#265]
Current State: In the property info page both breadcrumbs which lead back to the Explore page lead the the all "all" page which has no map instead of the updated one.

AC: Both breadcrumb links to lead to the updated explore page.![2022-03-10 10.11.09 AM.gif](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/dd031e3f-a1e1-45e8-9fc2-ad79978c6937)

**Comment by xdemocle** [comment]
this can ber closed. #233 will fix it

**Comment by StilyanMitrev** [comment]
closing
