### ISSUE TITLE
Can't claim rent if delist

### ISSUE THREAD

**Issue by StilyanMitrev** [EnterDAO/LandWorks-FE#287]
Given I'm a landlord and I have a property which has unclaimed rent listed, when i delist it without having my rent claimed - the claim rent button becomes inactive, this i cannot my pending rent.

Delisting a property which has rent to be claimed:
![2022-03-15 3.45.04 PM.gif](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/8b9c270f-e242-4021-936a-9b4e4a5b7659)

State of the same property after the tx went through and it is in a delisted state:
![Screenshot 2022-03-15 at 3.50.09 PM.png](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/0dc0b97f-a446-45e0-94b3-00d3bb01f37b)

**Comment by failfmi** [comment]
fixed
