### ISSUE TITLE
Change the warning when min rent period > max rent period

### ISSUE THREAD

**Issue by StilyanMitrev** [EnterDAO/LandWorks-FE#289]
At the moment the warning states that min rent period exceeds max rent period:

![Screenshot 2022-03-15 at 6.19.36 PM.png](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/91213197-1971-4dc8-aa45-862bc6e9baf6)

To be changed as in the [design for editing a listing](https://www.figma.com/file/gMFxv9DjmUkHbZQSe4lu5E/EnterDAO-Projects?node-id=5279%3A17476) to "Min period should be equal or smaller than Max period"

**Comment by entrxyz** [comment]
@failfmi the message is OK now but I see when I enter for example Min Period: 2 and Max Period: 1 , although the min is higher than the max, I can still Approve and it triggers a transaction. When I enter for example 22 or 222 then it triggers the validation and it's all good. Can you please check this and I'm not sure if its something you can fix or needs to go through Anzette as she was working on the property listing? Thanks.

**Comment by entrxyz** [comment]
My bad, was a cache issue. All good now. ;)

**Comment by StilyanMitrev** [comment]
text still remains "min rent period exceeds max rent period" on my end after cleaning my cache

**Comment by failfmi** [comment]
Could you test it out again?
