### ISSUE TITLE
Next available slot for rent incorrect

### ISSUE THREAD

**Issue by StilyanMitrev** [EnterDAO/LandWorks-FE#329]
For this property: https://landworks.xyz/property/17
It says that it is available for rent after 3.51 days.
However the active rent is until 08.04 which is more than 3.51 days.

Can we check if this is an individual case or a bug?![Screenshot 2022-03-21 at 4.51.07 PM.png](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/30ad0df4-3a16-4b99-b2ff-a7f4d926561a)

**Comment by mishaadzh** [comment]
in the latest version, the countdown is displayed correctly
![image](https://user-images.githubusercontent.com/95101208/159433637-ed042e00-92ee-400d-9dab-3395f2c60f4e.png)

**Comment by StilyanMitrev** [comment]
This is my misunderstanding around the logic for the next available slot for rent.
The next available slot for rent timestamp may be <> the next timestamp of the end of the current active rent because available slot for next rent is dictated by the min rent period + rent queue. Thanks @failfmi. Closing.
