### ISSUE TITLE
Status label in property shouldn't be clickable

### ISSUE THREAD

**Issue by StilyanMitrev** [EnterDAO/LandWorks-FE#394]
The status label (Available/Delisted/Rented) in property details is clickable and it shouldn't be as it's just a label.
![Screenshot 2022-03-28 at 16.19.44.png](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/58d6c394-b04b-4491-9e56-f5e8abb9fac7)

**Comment by entrxyz** [comment]
Confirmed
