### ISSUE TITLE
As a user I want to be able to claim all available rents regardless of the metaverses so I can do it all in a single tx

### ISSUE THREAD

**Issue by StilyanMitrev** [EnterDAO/LandWorks-FE#480]
We need to make sure that the claim modal lists all properties where there is rent to be claimed.
We need to make sure users can claim rents for multiple properties form different metaverses at one.

AC1: Given I have rent to be claimed for properties from >1 metaverse, then I should see all of them when I open the claim rents modal.
AC2: Given I want to claim all my available rent, then I should be able to claim rent for properties form >1 metaverse in a single tx.

![Select the properties you want to claim your rent for.png](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/fcfbce52-707d-46eb-9c31-09ddfc9493a9)

**Comment by failfmi** [comment]
This is possible.
