### ISSUE TITLE
As a user I want to be able to hide the dynamic map so i can view more properties on the Explore page

### ISSUE THREAD

**Issue by StilyanMitrev** [EnterDAO/LandWorks-FE#502]
At the moment there is only a single view on the Explore page - property cards and a dynamic map.
We received a signal form the community that they would like to view more properties in the explore page (similar to the different views in opensea).
Therefore we need to add a view where the dynamic map is hidden (for Decentraland). This view will also enable the generic integration of other metaverses as not all of them will support a dynamic map.

Design is [here](https://www.figma.com/file/gMFxv9DjmUkHbZQSe4lu5E/EnterDAO-Projects?node-id=8288%3A18778).

Basically we need to add:
- label indicating how many properties are currently showed (same number as the label in the header)
- icons for changing the view
![Screenshot 2022-04-15 at 14.18.03.png](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/af84bf12-4f3f-44d5-ba82-91a143d27898)

The expected functionality:
- Icons will be to switch view (with and without map) when clicked.
- Icon with active view should be highlighted.
- For generic metaverse integration - no map view would be the default one and the map view would be inactive.

AC1: Given I want to view more properties on the Explore Page, when i click the view icon then the dynamic map will hide and I will see more properties on the page.
AC2: Given I have selected a generic metaverse, then the default view on the Explore Page is the one without a map and the dynamic map icon is inactive.

**Comment by failfmi** [comment]
I think that if the selected metaverse is != `Decentraland` (you can compare it to `1`), we should not be able to show the map.

**Comment by StilyanMitrev** [comment]
I think 4 columns looks a bit stretched when open the page on my monitor (1920x1080).
But on my macbook sceen it looks okay (2560x1600)
Can we add an extra column so they can be 5 once aspect ration > 16:10?

Picture below is from my monitor:
![image.png](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/827a9836-49ce-4337-b58e-6a27f1b37b44)

**Comment by StilyanMitrev** [comment]
On 2560x1440 and 1920x1080 there used to be 3 columns of properties on the map view and now there are only 2 

![image.png](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/79ce88fa-8dc6-4cf8-807d-93cf69a4477e)

**Comment by StilyanMitrev** [comment]
Also the 5 column view seems a bit stretched again and I believe we can have 6 columns.
Can we have the default width of the cards the same as in My Properties in order to:
- fit max 6 columns regardless of how big the resolution gets
- if resolution can fit > 6 properties - add padding on the sides of the webpage like we have in "My Properties"
- allow max stretch of cards = as in "My Properties"
