### ISSUE TITLE
Styling issues after antd removal

### ISSUE THREAD

**Issue by failfmi** [EnterDAO/LandWorks-FE#596]

**Comment by failfmi** [comment]
Rent history `Cost` token icon
![image](https://user-images.githubusercontent.com/20928965/167363228-28e1f72c-e894-4fee-b163-6239fe0cc021.png)

**Comment by failfmi** [comment]
* Property details Nearby properties
![image](https://user-images.githubusercontent.com/20928965/167363357-678847da-9a45-433b-a268-5ccedd9ed59b.png)

**Comment by failfmi** [comment]
* Property details Rent History > `Yours`
![image](https://user-images.githubusercontent.com/20928965/167363478-3cb8fe3b-17b9-44ec-8742-8c7afb823dac.png)

**Comment by failfmi** [comment]
Rent modal > token icon
![image](https://user-images.githubusercontent.com/20928965/167363636-a9edbe23-077c-4f67-9b77-8f443e66b740.png)

**Comment by failfmi** [comment]
My properties:
* Rent history token icon
* Claim history token icon

**Comment by zetske** [comment]
> * Property details Nearby properties
>   ![image](https://user-images.githubusercontent.com/20928965/167363357-678847da-9a45-433b-a268-5ccedd9ed59b.png)

I don't see this styling bug anymore
