### ISSUE TITLE
Search in My properties does not work

### ISSUE THREAD

**Issue by failfmi** [EnterDAO/LandWorks-FE#612]
When I try to search in My Properties through my properties, nothing is changed.

**Comment by StilyanMitrev** [comment]
When i try to search for "land (", the moment i type in "(", the page throws an error.
This is both in the My Properties and Explore search bars.
We need to understand what causes it and if there are other chars that trigger this error.

![2022-05-16 09.29.07.gif](https://images.zenhubusercontent.com/621494fdbdc5123f7802bb6a/9ec2895e-51e4-4e34-9526-43d89b3915cd)
