### ISSUE TITLE
Drop Down Styling

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [EnterDAO/LandWorks-FE#98]
1. Not styled like in the designs (rounded);
2. The selected option should be the one in blue, not the fire icon only;
3. The arrow changes position when dropdown is expanded (this is valid for all drop downs across the app)

**Comment by StilyanMitrev** [comment]
Different dropdowns in the redesigned UI. Maybe obsolete.

**Comment by StilyanMitrev** [comment]
obsolete as it is regarding initial design
